apiVersion: apps/v1
kind: Deployment
metadata:
name: interface
labels:
  app: interface
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: interface
      tier: interface
  spec:
    containers:
    - name: interface
      image: gcr.io/automatictrainingcicd/interface@sha256:e26813a9aac582e468087c8962aac964f9962b796eab910a4e7a2573865ea5e1
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
        name: hello

---
apiVersion: v1
kind: Service
metadata:
name: interface
labels:
  app: interface
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: interface
  tier: interface
type: LoadBalancer