apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface
  labels:
    app: interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interface
  template:
    metadata:
      labels:
        app: interface
    spec:
      containers:
      - name: interface
        image: gcr.io/automatictrainingcicd/interface:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: interface
  labels:
    app: interface
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: hello
    tier: hello
  type: LoadBalancer