apiVersion: v1
kind: Pod
metadata:
  name: gke-interface
  labels:
    name: gke-interface
spec:
  containers:
    - name: interface
      image: gcr.io/automatictrainingcicd/interface:latest
      ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: interface
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    name: interface